session:
  secret: session-secret

cookie:
  secret: cookie-secret

port: 3001

logger:
  streams:
    -
      level: debug
      path: logs/api/test.log
      type: rotating-file
      period: 1d
      count: 2
